export const pageLocations = [
    {
      location_id: 106078429431815,
      location_name: "London, United Kingdom",
      currency_rate: 1.25,
      facebook_monetized: true,
    },
    {
      location_id: 1,
      location_name: "United States",
      currency_rate: 1.0,
      facebook_monetized: true,
    },
    {
      location_id: 3,
      location_name: "Switzerland",
      currency_rate: 1.09,
      facebook_monetized: true,
    },
    {
      location_id: 41,
      location_name: "Slovenia",
      currency_rate: 1.08,
      facebook_monetized: true,
    },
    {
      location_id: 42,
      location_name: "Croatia",
      currency_rate: 1.08,
      facebook_monetized: true,
    },
    {
      location_id: 43,
      location_name: "Lithuania",
      currency_rate: 1.08,
      facebook_monetized: true,
    },
    {
      location_id: 44,
      location_name: "Latvia",
      currency_rate: 1.08,
      facebook_monetized: true,
    },
    {
      location_id: 45,
      location_name: "Estonia",
      currency_rate: 1.08,
      facebook_monetized: true,
    },
    {
      location_id: 46,
      location_name: "Cyprus",
      currency_rate: 1.08,
      facebook_monetized: true,
    },
    {
      location_id: 4,
      location_name: "Norway",
      currency_rate: 0.09,
      facebook_monetized: true,
    },
    {
      location_id: 5,
      location_name: "Australia",
      currency_rate: 0.65,
      facebook_monetized: true,
    },
    {
      location_id: 6,
      location_name: "Canada",
      currency_rate: 0.74,
      facebook_monetized: true,
    },
    {
      location_id: 7,
      location_name: "Singapore",
      currency_rate: 0.74,
      facebook_monetized: true,
    },
    {
      location_id: 16,
      location_name: "New Zealand",
      currency_rate: 0.65,
      facebook_monetized: true,
    },
    {
      location_id: 8,
      location_name: "Japan",
      currency_rate: 0.0075,
      facebook_monetized: true,
    },
    {
      location_id: 9,
      location_name: "Hong Kong",
      currency_rate: 0.13,
      facebook_monetized: true,
    },
    {
      location_id: 10,
      location_name: "South Korea",
      currency_rate: 0.00076,
      facebook_monetized: true,
    },
    {
      location_id: 11,
      location_name: "Saudi Arabia",
      currency_rate: 0.27,
      facebook_monetized: true,
    },
    {
      location_id: 12,
      location_name: "Qatar",
      currency_rate: 0.27,
      facebook_monetized: true,
    },
    {
      location_id: 13,
      location_name: "United Arab Emirates",
      currency_rate: 0.27,
      facebook_monetized: true,
    },
    {
      location_id: 14,
      location_name: "Israel",
      currency_rate: 0.26,
      facebook_monetized: true,
    },
    {
      location_id: 102161913158207,
      location_name: "India",
      currency_rate: 0.012, // 1 INR = 0.012 USD
      facebook_monetized: true,
    },
    {
      location_id: 101889586519301,
      location_name: "Bangladesh",
      currency_rate: 0.0095,
      facebook_monetized: true,
    },
  ];